export const shortlistedTeams = [
  { id: 1, teamName: "Team Magnificent", leaderName: "Aftab Sayed" },
  { id: 2, teamName: "Bitstorm", leaderName: "Spoorthi Patil" },
  { id: 3, teamName: "Code drifters", leaderName: "Anushka Bakale" },
  { id: 4, teamName: "Cognicast", leaderName: "Medhini Kulkarni" },
  { id: 5, teamName: "Binary Busters", leaderName: "Sakshi A Vanakundre" },
  { id: 6, teamName: "IMMORTAL'S", leaderName: "Sumit Pujari" },
  { id: 7, teamName: "Synapse", leaderName: "Amogh Honnalli" },
  { id: 8, teamName: "Hack Horizon", leaderName: "Madhav P" },
  { id: 9, teamName: "Segmentation Squad", leaderName: "M K Nasiruddin" },
  { id: 10, teamName: "She Codes", leaderName: "Jyothirmai Gowda V S" },
  { id: 11, teamName: "Codeflux", leaderName: "Vishwaradhya Hiremath" },
  { id: 12, teamName: "Hackmate", leaderName: "Sinchana Parashetti" },
  { id: 13, teamName: "CodeQuest", leaderName: "Gnanasree B" },
  { id: 14, teamName: "Agdi rulers", leaderName: "Prajwal Bashetti" },
  { id: 15, teamName: "BOT BUILDERS", leaderName: "Shreya Kotur" },
  { id: 16, teamName: "Code Fusion", leaderName: "Vandana Alawandi" },
  { id: 17, teamName: "Team Diamond", leaderName: "Balaji" },
  { id: 18, teamName: "Alpha Hackers", leaderName: "Amit Mavinakatti" },
  { id: 19, teamName: "The A-TEAM", leaderName: "Rahul Vernekar" },
  { id: 20, teamName: "Tech titans", leaderName: "Anjali Sagaram" },
  { id: 21, teamName: "Prism", leaderName: "Bhoomika Raikar" },
  { id: 22, teamName: "Quad coders", leaderName: "Hamid M" },
  { id: 23, teamName: "Matrix", leaderName: "Irappa Mali" },
  { id: 24, teamName: "BeyondMinus", leaderName: "Mallikarjun Paroji" },
  { id: 25, teamName: "Tech Tank", leaderName: "Mani Kanta" },
  { id: 26, teamName: "Digital Disruptors", leaderName: "Praveen Balannavar" },
  { id: 27, teamName: "Titans", leaderName: "Tejaswini Dalal" },
  { id: 28, teamName: "Curious minds", leaderName: "Kavya Poojar" },
  { id: 29, teamName: "Cryptara", leaderName: "Keerthi Sindogi" },
  { id: 30, teamName: "Quantum Coders", leaderName: "Swati Mestri" },
  { id: 31, teamName: "Cozy Coder", leaderName: "Rukhaiya Tadkod" },
  { id: 32, teamName: "The core coders", leaderName: "Pranav Angadi" },
  { id: 33, teamName: "We Code Together", leaderName: "Akash" },
  { id: 34, teamName: "Brain Hackers", leaderName: "Rakshit Kulkarni" },
  { id: 35, teamName: "AryaaCode", leaderName: "Abhay Hotagi" },
  { id: 36, teamName: "404 Ninjas", leaderName: "Preetam Karoshi" },
  { id: 37, teamName: "Novanex", leaderName: "Adithi Satyappanavar" },
  { id: 38, teamName: "HACKSTORM", leaderName: "Md Toufeeq Ahmed" },
  { id: 39, teamName: "codex", leaderName: "Maniyar Zahid Ahmed" },
  { id: 40, teamName: "Vibe tribes", leaderName: "Vandana Mulkigoudra" },
  { id: 41, teamName: "CODE INVADERS", leaderName: "Shankargouda Patil" },
  { id: 42, teamName: "GATE 404 Delayed", leaderName: "Girish gouda N" },
  { id: 43, teamName: "TechNova", leaderName: "Harshita J Meti" },
  { id: 44, teamName: "ThunderBolt", leaderName: "Mallikarjun Badiger" },
  { id: 45, teamName: "404 Crackers", leaderName: "Anand Bolaji" },
  { id: 46, teamName: "Run Time Error", leaderName: "Nilam Patil" },
  { id: 47, teamName: "CIRCUIT BREAKERS", leaderName: "Saniya S Mirza" },
  { id: 48, teamName: "Xyro", leaderName: "Shashank Hallur" },
  { id: 49, teamName: "Codebreakers", leaderName: "Srujan Hariwal" },
  { id: 50, teamName: "Code Comets", leaderName: "Supreeth Bhosale" }
];
